#!/bin/bash -e

trap 'echo "ERROR: $BASH_SOURCE:$LINENO $BASH_COMMAND" >&2' ERR

mkdir -p /ssl/webroot

# Depend on the nginx service to be up (so that Let's encrypt can potentially
# immediately create some keys for which it needs a running HTTP server).
while ! pgrep -P 1 nginx >/dev/null ; do
  sleep 1
done

# docker-gen logs to stderr, so we redirect it to stdout.
exec /dockergen/docker-gen -config /dockergen/dockergen.conf 2>&1
