#!/bin/bash -e

mkdir -p /ssl/webroot

# Depend on the nginx service to be up (so that Let's encrypt can potentially
# immediately create some keys for which it needs a running HTTP server).
while ! pgrep -P 1 nginx >/dev/null ; do
  sleep 1
done

exec /dockergen/docker-gen -config /dockergen/dockergen.conf 2>&1
