#!/bin/bash -e

# We source this file to gain access to environment variables provided to Docker container.
# We need access to at least LETSENCRYPT_EMAIL.
. /dev/shm/cron-environment

/letsencrypt/dockergen.sh
