#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/dockergen
  chown nobody:nogroup /var/log/dockergen

  exec chpst -u nobody:nogroup svlogd -tt /var/log/dockergen
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?P<time___time__LogDateTime>\\d+/\\d+/\\d+ \\d+:\\d+:\\d+) (?P<msg>.+?)\\s*$"
fi
