#!/bin/bash -e

if [ "${LOG_TO_STDOUT}" != "1" ]; then
  mkdir -p /var/log/dnsmasq
  chown nobody:nogroup /var/log/dnsmasq

  exec chpst -u nobody:nogroup svlogd -tt /var/log/dnsmasq
else
  exec chpst -u nobody:nogroup regex2json "^\\s*(?P<time___time__Stamp>.+?) dnsmasq\\[(?P<pid___int>\\d+)\\]: (?P<msg>.+?)\\s*$"
fi
